apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
      tier: backend
  serviceName: postgres
  replicas: 2
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: postgres
        tier: backend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: postgres
        name: postgres
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: psql-pass
              key: password
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: psql-persistent-storage
          mountPath: /var/lib/postgres
      volumes:
      - name: psql-persistent-storage
        persistentVolumeClaim:
          claimName: psql-pv-claim
