apiVersion: apps/v1
kind: Deployment
metadata:
  name: behav-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: behav-app
  template:
    metadata:
      labels:
        app: behav-app
    spec:
      containers:
      - name: behav-app
        image: filipossantos/python-test:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: postgres
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: "password"
